# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: github CI

on:
  push:
    branches:
      - master
      - dev
      - coverity_scan
      - add_test_2CI
  pull_request:
    branches:
      - master
      - dev
      - coverity_scan

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
      - name: Set up JDK 8
        uses: actions/setup-java@91d3aa4956ec4a53e477c4907347b5e3481be8c9
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: buildcahe
        run: |
          git clone https://github.com/ctripcorp/x-pipe.git
          cd x-pipe
          git checkout mvn_repo
          sh install.sh

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-2022-11-30-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-2022

      - name: Build with Maven
        #run: mvn clean install -Plocal -Dmaven.test.failure.ignore=true
        run: mvn clean install -Plocal

      - name: codecov
        uses: codecov/codecov-action@c585afe366f940d214dc09df2664c06d7fe07052
        with:
          token: 50484ce1-6e23-4309-87ac-e2cf9d3a3b4f
          file: ${{ github.workspace }}/**/target/site/jacoco/jacoco.xml

      - name: Upload coverage to codecov
        run: curl -s https://codecov.io/bash | bash
